//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfomation
    {
        public int bankId { get; set; }
        public string bankName { get; set; }
        public string nameCard { get; set; }
        public Nullable<int> bankNumber { get; set; }
        public string bankChiNhanh { get; set; }
        public int glId { get; set; }
    
        public virtual glAccount glAccount { get; set; }
    }
}
