//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfor
    {
        public long bankID { get; set; }
        public string bankName { get; set; }
        public string nameCard { get; set; }
        public long bankNumber { get; set; }
        public string chiNhanh { get; set; }
        public long glID { get; set; }
    
        public virtual GLAccount GLAccount { get; set; }
    }
}
