//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GolikeEntities : DbContext
    {
        public GolikeEntities()
            : base("name=GolikeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankInfor> BankInfors { get; set; }
        public virtual DbSet<FBAccount> FBAccounts { get; set; }
        public virtual DbSet<GLAccount> GLAccounts { get; set; }
        public virtual DbSet<GLInfor> GLInfors { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<StatusTable> StatusTables { get; set; }
    }
}
