//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fbAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fbAccount()
        {
            this.jobs = new HashSet<job>();
        }
    
        public int fiID { get; set; }
        public int fbUid { get; set; }
        public string fbPassword { get; set; }
        public string fb2Fa { get; set; }
        public string fbStatus { get; set; }
        public string fbGhiChu { get; set; }
        public int glId { get; set; }
    
        public virtual glAccount glAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job> jobs { get; set; }
    }
}
