//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class glInformation
    {
        public int glInfoId { get; set; }
        public string glEmail { get; set; }
        public string glFullName { get; set; }
        public int glPhone { get; set; }
        public int glSodu { get; set; }
        public int glLamlai { get; set; }
        public int glId { get; set; }
        public int glChoDuyet { get; set; }
    
        public virtual glAccount glAccount { get; set; }
    }
}
