//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLInfor
    {
        public long glInforID { get; set; }
        public string glEmail { get; set; }
        public string glFullname { get; set; }
        public long glPhone { get; set; }
        public long glSodu { get; set; }
        public long glLamlai { get; set; }
        public long glID { get; set; }
        public long glChoduyet { get; set; }
    
        public virtual GLAccount GLAccount { get; set; }
    }
}
