//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int jobId { get; set; }
        public string jobStatus { get; set; }
        public string jobLink { get; set; }
        public string jobAction { get; set; }
        public int fbId { get; set; }
    
        public virtual fbAccount fbAccount { get; set; }
    }
}
