//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public long jobID { get; set; }
        public string jobstatus { get; set; }
        public string jobLink { get; set; }
        public string jobAction { get; set; }
        public long fbID { get; set; }
    
        public virtual FBAccount FBAccount { get; set; }
    }
}
