//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusTable
    {
        public int statusId { get; set; }
        public string statusContent { get; set; }
        public int gdId { get; set; }
    
        public virtual glAccount glAccount { get; set; }
    }
}
